DROP TABLE GETBURGER_RPT CASCADE CONSTRAINTS;

CREATE TABLE GETBURGER_RPT
(
  ID              INTEGER,
  BSN             VARCHAR2(4000 BYTE),
  GESLACHTSNAAM   VARCHAR2(4000 BYTE),
  VOORNAMEN       VARCHAR2(4000 BYTE),
  DATUM           DATE,
  MIN_TIJD        TIMESTAMP(6),
  MAX_TIJD        TIMESTAMP(6),
  AANTAL_WS_CALL  NUMBER,
  MIN_VERWERK     NUMBER,
  MAX_VERWERK     NUMBER,
  AVG_VERWERK     NUMBER,
  WEBMETHODE      CHAR(17 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


