DROP TABLE ANTWOORD CASCADE CONSTRAINTS;

CREATE TABLE ANTWOORD
(
  ANTWOORD_KEY       NUMBER                     NOT NULL,
  VERSTUURDTIJD      TIMESTAMP(6),
  VERWERK_MILLIS     NUMBER,
  INHOUD             CLOB,
  HOST_ID            VARCHAR2(4000 BYTE),
  ESB_ID             VARCHAR2(4000 BYTE),
  STATUS             VARCHAR2(4000 BYTE),
  BERICHT_GROOTTE    NUMBER,
  TRANSACTIE_ID      NUMBER,
  VERSIESTUF         VARCHAR2(4000 BYTE),
  SECTORMODEL        VARCHAR2(4000 BYTE),
  VERSIESECTORMODEL  VARCHAR2(4000 BYTE),
  BERICHTCODE        VARCHAR2(4000 BYTE),
  ZENDER_ORG         VARCHAR2(4000 BYTE),
  ZENDER_APP         VARCHAR2(4000 BYTE),
  ZENDER_ADM         VARCHAR2(4000 BYTE),
  ZENDER_GBR         VARCHAR2(4000 BYTE),
  ONTVANGER_ORG      VARCHAR2(4000 BYTE),
  ONTVANGER_APP      VARCHAR2(4000 BYTE),
  ONTVANGER_ADM      VARCHAR2(4000 BYTE),
  ONTVANGER_GBR      VARCHAR2(4000 BYTE),
  REFERENTIENUMMER   VARCHAR2(4000 BYTE),
  TIJDSTIPBERICHT    VARCHAR2(4000 BYTE),
  CROSSREFNUMMER     VARCHAR2(4000 BYTE),
  ENTITEITTYPE       VARCHAR2(4000 BYTE),
  FUNCTIE            VARCHAR2(4000 BYTE),
  WEBMETHODE         VARCHAR2(4000 BYTE),
  MESSAGEID          VARCHAR2(4000 BYTE),
  CORRELATIONID      VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

prompt ALTER TABLE ANTWOORD
alter table antwoord add (
  constraint antwoord_pk primary key ( antwoord_key ));

