DROP TABLE GETBURGERSUBSERVICE_RPT CASCADE CONSTRAINTS;

CREATE TABLE GETBURGERSUBSERVICE_RPT
(
  ID             INTEGER,
  BSN            VARCHAR2(4000 BYTE),
  DATUM          DATE,
  VERSTUURDTIJD  DATE,
  RESPONSE_TIJD  NUMBER,
  WEBMETHODE     CHAR(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


