/**
|||-----------------------------------------------------------------------
|||OMSCHRIJVING:
|||  
|||
|||PARAMETERS:
|||
|||OPMERKINGEN:
|||
|||SUBVERSION INFO : DO NOT CHANGE!!!!
|||  $Date: 2011-04-29 10:01:47 +0200 (Fri, 29 Apr 2011) $                       
|||  $Revision: 5998 $                   
|||  $Author: nanne $                     
|||  $URL: svn://store01/fqt-db/Constraints/URP_constraints.sql $                        
|||  $ID: $                         
|||-----------------------------------------------------------------------
**/
ALTER TABLE URP_USERS_TAB ADD (
  CONSTRAINT URP_USR_CHK_USERNAME CHECK (   (USERNAME like '%rotterdam.nl') 
                                         or (USERNAME like 'meta%')
                                         or (USERNAME like '%epsvenue.com')
                                         or (USERNAME like '%keizerkarelpodia.nl') 
                                         or (USERNAME like '%assai.nl') 
                                        ) 
                               );


ALTER TABLE URP_USERS_TAB ADD (
  CONSTRAINT URP_USR_PK PRIMARY KEY (ID));

ALTER TABLE URP_USERS_TAB ADD (
  CONSTRAINT URP_USR_UK UNIQUE (USERNAME));


ALTER TABLE URP_ROLES ADD (
  CONSTRAINT URP_RLE_PK PRIMARY KEY (ID));

ALTER TABLE URP_ROLES ADD (
  CONSTRAINT URP_RLE_UK UNIQUE (ROLENAME));


ALTER TABLE URP_PERMISSIONS ADD (
  CONSTRAINT URP_PMS_PK PRIMARY KEY (ID));

ALTER TABLE URP_PERMISSIONS ADD (
  CONSTRAINT URP_PMS_UK UNIQUE (NAME));


ALTER TABLE URP_USER_ROLE ADD (
  CONSTRAINT URP_URL_PK PRIMARY KEY (ID));

ALTER TABLE URP_USER_ROLE ADD (
  CONSTRAINT URP_URL_UK UNIQUE (USR_ID, RLE_ID));

--  ALTER TABLE URP_USER_ROLE ADD (
--    CONSTRAINT URP_URL_USR_FK FOREIGN KEY (USR_ID) 
--      REFERENCES URP_USERS (ID)
--      ON DELETE CASCADE);
--  
ALTER TABLE URP_USER_ROLE ADD (
  CONSTRAINT URP_URL_RLE_FK FOREIGN KEY (RLE_ID) 
    REFERENCES URP_ROLES (ID));


ALTER TABLE URP_ROLE_PERMISSION ADD (
  CONSTRAINT URP_RPM_PK PRIMARY KEY (ID));

ALTER TABLE URP_ROLE_PERMISSION ADD (
  CONSTRAINT URP_RPM_UK UNIQUE (RLE_ID, PMS_ID));

ALTER TABLE URP_ROLE_PERMISSION ADD (
  CONSTRAINT URP_RPM_RLE_FK FOREIGN KEY (RLE_ID) 
    REFERENCES URP_ROLES (ID));

ALTER TABLE URP_ROLE_PERMISSION ADD (
  CONSTRAINT URP_RPM_PMS_FK FOREIGN KEY (PMS_ID) 
    REFERENCES URP_PERMISSIONS (ID)
    ON DELETE CASCADE);


ALTER TABLE URP_MENUNODES ADD (
  CONSTRAINT URP_MENU_PK PRIMARY KEY (ID));

ALTER TABLE URP_MENUNODES ADD (
  CONSTRAINT URP_MENU_UK UNIQUE (MENUNAME));

ALTER TABLE URP_MENUNODES ADD (
  CONSTRAINT URP_MENU_MENU_FK FOREIGN KEY (PARENT_ID) 
    REFERENCES URP_MENUNODES (ID)
    ON DELETE CASCADE);

ALTER TABLE URP_PERMISSIONS ADD (
  CONSTRAINT URP_PMS_MENU_FK FOREIGN KEY (MENU_ID) 
    REFERENCES URP_MENUNODES (ID)
    ON DELETE CASCADE);

ALTER TABLE URP_PERMISSIONS ADD (
  CONSTRAINT URP_PMS_SQL_FK FOREIGN KEY (SQL_ID) 
    REFERENCES SQM_QUERIES (ID));

ALTER TABLE URP_PERMISSIONS ADD (
  CONSTRAINT URP_PMS_CON_FK FOREIGN KEY (CON_ID) 
    REFERENCES SQM_CONNECTIONS (ID));

