PROMPT CREATE OR REPLACE TRIGGER ATA_PAR_TRG_BRIU
CREATE OR REPLACE TRIGGER ATA_PAR_TRG_BRIU
BEFORE INSERT OR UPDATE OR DELETE
ON ATA_PARAMETERS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
    IF INSERTING THEN
      :NEW.rv := 1;
      SELECT ATA_sequence.NEXTVAL INTO :NEW.id FROM dual;
    ELSIF UPDATING
    THEN
      :NEW.rv := :OLD.rv + 1;
    END IF;
END
;
/
