ALTER TABLE URP_USERS ADD (
  CONSTRAINT URP_USR_CHK_RDAM_USERNAME CHECK ((USERNAME like '%rotterdam.nl') or (USERNAME like 'meta%')) );


ALTER TABLE URP_USERS ADD (
  CONSTRAINT URP_USR_PK PRIMARY KEY (ID));

ALTER TABLE URP_USERS ADD (
  CONSTRAINT URP_USR_UK UNIQUE (USERNAME));


ALTER TABLE URP_ROLES ADD (
  CONSTRAINT URP_RLE_PK PRIMARY KEY (ID));

ALTER TABLE URP_ROLES ADD (
  CONSTRAINT URP_RLE_UK UNIQUE (ROLENAME));


ALTER TABLE URP_PERMISSIONS ADD (
  CONSTRAINT URP_PMS_PK PRIMARY KEY (ID));

ALTER TABLE URP_PERMISSIONS ADD (
  CONSTRAINT URP_PMS_UK UNIQUE (VALUE));


ALTER TABLE URP_USER_ROLE ADD (
  CONSTRAINT URP_URL_PK PRIMARY KEY (ID));

ALTER TABLE URP_USER_ROLE ADD (
  CONSTRAINT URP_URL_UK UNIQUE (USR_ID, RLE_ID));

ALTER TABLE URP_USER_ROLE ADD (
  CONSTRAINT URP_URL_USR_FK FOREIGN KEY (USR_ID) 
    REFERENCES URP_USERS (ID)
    ON DELETE CASCADE);

ALTER TABLE URP_USER_ROLE ADD (
  CONSTRAINT URP_URL_RLE_FK FOREIGN KEY (RLE_ID) 
    REFERENCES URP_ROLES (ID));


ALTER TABLE URP_ROLE_PERMISSION ADD (
  CONSTRAINT URP_RPM_PK PRIMARY KEY (ID));

ALTER TABLE URP_ROLE_PERMISSION ADD (
  CONSTRAINT URP_RPM_UK UNIQUE (RLE_ID, PMS_ID));

ALTER TABLE URP_ROLE_PERMISSION ADD (
  CONSTRAINT URP_RPM_RLE_FK FOREIGN KEY (RLE_ID) 
    REFERENCES URP_ROLES (ID));

ALTER TABLE URP_ROLE_PERMISSION ADD (
  CONSTRAINT URP_RPM_PMS_FK FOREIGN KEY (PMS_ID) 
    REFERENCES URP_PERMISSIONS (ID)
    ON DELETE CASCADE);


